# настройки сервера
server:
  port: 8082

spring:
  application:
    name: task-service

  # настройки подключения к базе данных h2
  datasource:
    url: jdbc:h2:mem:taskdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # настройки jpa и hibernate
  jpa:
    hibernate:
      ddl-auto: none             # создание таблиц через liquibase
    show-sql: true

  # h2 консоль для просмотра таблиц
  h2:
    console:
      enabled: true

  # настройки liquibase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml