services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - task-network

  task-service:
    build:
      context: ./task_service
      dockerfile: Dockerfile
    container_name: task-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - task-network

volumes:
  postgres_data:

networks:
  task-network:
    driver: bridge