name: Docker Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JARs
        run: |
          cd user_service && mvn clean package -DskipTests
          cd ../task_service && mvn clean package -DskipTests

      - name: Build with Docker Compose
        run: docker compose up -d --build

      - name: Check services
        run: docker ps